# Generated by Django 4.1 on 2023-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enroller_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroller',
            name='wait',
            field=models.BooleanField(default=False),
        ),
    ]
