# Generated by Django 4.1 on 2023-07-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_enroller_time_alter_enroller_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroller',
            name='Time',
            field=models.TimeField(),
        ),
    ]
