# Generated by Django 4.1 on 2023-07-19 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_enroller_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroller',
            name='Time',
        ),
        migrations.AddField(
            model_name='enroller',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
